(DEFINE (DOMAIN LOGISTICS)
 (:REQUIREMENTS :STRIPS)
 (:TYPES PACKAGE - OBJECT
         TRUCK - OBJECT
         AIRPLANE - OBJECT
         AIRPORT - OBJECT
         LOCATION - OBJECT
         CITY - OBJECT)

 (:PREDICATES
  (IN ?OBJ - OBJECT ?OBJ - OBJECT)
  (AT ?OBJ - OBJECT ?LOC - OBJECT)
  (IN-CITY ?OBJ - OBJECT ?CITY - OBJECT))

 (:ACTION LOAD-TRUCK
  :PARAMETERS (?OBJ - PACKAGE ?TRUCK - TRUCK ?LOC - LOCATION)
  :PRECONDITION (AND (AT ?TRUCK ?LOC)
                     (AT ?OBJ ?LOC))
  :EFFECT (AND (NOT (AT ?OBJ ?LOC))
               (IN ?OBJ ?TRUCK)))

 (:ACTION LOAD-AIRPLANE
  :PARAMETERS (?OBJ - PACKAGE ?AIRPLANE - AIRPLANE ?LOC - LOCATION)
  :PRECONDITION (AND (AT ?OBJ ?LOC)
                     (AT ?AIRPLANE ?LOC))
  :EFFECT (AND (NOT (AT ?OBJ ?LOC))
               (IN ?OBJ ?AIRPLANE)))

 (:ACTION UNLOAD-TRUCK
  :PARAMETERS (?OBJ - PACKAGE ?TRUCK - TRUCK ?LOC - LOCATION)
  :PRECONDITION (AND (AT ?TRUCK ?LOC)
                     (IN ?OBJ ?TRUCK))
  :EFFECT (AND (NOT (IN ?OBJ ?TRUCK))
               (AT ?OBJ ?LOC)))

 (:ACTION UNLOAD-AIRPLANE
  :PARAMETERS (?OBJ - PACKAGE ?AIRPLANE - AIRPLANE ?LOC - LOCATION)
  :PRECONDITION (AND (IN ?OBJ ?AIRPLANE)
                     (AT ?AIRPLANE ?LOC))
  :EFFECT (AND (NOT (IN ?OBJ ?AIRPLANE))
               (AT ?OBJ ?LOC)))

 (:ACTION DRIVE-TRUCK
  :PARAMETERS (?TRUCK - TRUCK ?LOC-FROM - LOCATION ?LOC-TO - LOCATION
               ?CITY - CITY)
  :PRECONDITION (AND (AT ?TRUCK ?LOC-FROM)
                     (IN-CITY ?LOC-FROM ?CITY)
                     (IN-CITY ?LOC-TO ?CITY))
  :EFFECT (AND (NOT (AT ?TRUCK ?LOC-FROM))
               (AT ?TRUCK ?LOC-TO)))

 (:ACTION FLY-AIRPLANE
  :PARAMETERS (?AIRPLANE - AIRPLANE ?LOC-FROM - AIRPORT ?LOC-TO - AIRPORT)
  :PRECONDITION (AND (AT ?AIRPLANE ?LOC-FROM))
  :EFFECT (AND (NOT (AT ?AIRPLANE ?LOC-FROM))
               (AT ?AIRPLANE ?LOC-TO))))
