(DEFINE (PROBLEM LOGISTICS-11-0)
 (:DOMAIN LOGISTICS)
 (:OBJECTS APN1 - AIRPLANE
           APT4 - AIRPORT
           POS4 - LOCATION
           APT3 - AIRPORT
           POS3 - LOCATION
           APT2 - AIRPORT
           POS2 - LOCATION
           APT1 - AIRPORT
           POS1 - LOCATION
           CIT4 - CITY
           CIT3 - CITY
           CIT2 - CITY
           CIT1 - CITY
           TRU4 - TRUCK
           TRU3 - TRUCK
           TRU2 - TRUCK
           TRU1 - TRUCK
           OBJ43 - PACKAGE
           OBJ42 - PACKAGE
           OBJ41 - PACKAGE
           OBJ33 - PACKAGE
           OBJ32 - PACKAGE
           OBJ31 - PACKAGE
           OBJ23 - PACKAGE
           OBJ22 - PACKAGE
           OBJ21 - PACKAGE
           OBJ13 - PACKAGE
           OBJ12 - PACKAGE
           OBJ11 - PACKAGE)

 (:INIT
  (LOCATION APT1)
  (LOCATION APT2)
  (LOCATION APT3)
  (LOCATION APT4)
  (AT APN1 APT3)
  (AT TRU1 POS1)
  (AT OBJ11 POS1)
  (AT OBJ12 POS1)
  (AT OBJ13 POS1)
  (AT TRU2 POS2)
  (AT OBJ21 POS2)
  (AT OBJ22 POS2)
  (AT OBJ23 POS2)
  (AT TRU3 POS3)
  (AT OBJ31 POS3)
  (AT OBJ32 POS3)
  (AT OBJ33 POS3)
  (AT TRU4 POS4)
  (AT OBJ41 POS4)
  (AT OBJ42 POS4)
  (AT OBJ43 POS4)
  (IN-CITY POS1 CIT1)
  (IN-CITY APT1 CIT1)
  (IN-CITY POS2 CIT2)
  (IN-CITY APT2 CIT2)
  (IN-CITY POS3 CIT3)
  (IN-CITY APT3 CIT3)
  (IN-CITY POS4 CIT4)
  (IN-CITY APT4 CIT4))
 (:GOAL
  (AND (AT OBJ33 APT1)
       (AT OBJ22 APT2)
       (AT OBJ43 POS4)
       (AT OBJ11 POS1)
       (AT OBJ23 POS1)
       (AT OBJ31 POS1)
       (AT OBJ12 APT2)
       (AT OBJ13 POS4)
       (AT OBJ42 APT2)
       (AT OBJ21 POS4)
       (AT OBJ41 POS4))))