(DEFINE (PROBLEM LOGISTICS-14-0)
 (:DOMAIN LOGISTICS)
 (:OBJECTS APN2 - AIRPLANE
           APN1 - AIRPLANE
           APT5 - AIRPORT
           POS5 - LOCATION
           APT4 - AIRPORT
           POS4 - LOCATION
           APT3 - AIRPORT
           POS3 - LOCATION
           APT2 - AIRPORT
           POS2 - LOCATION
           APT1 - AIRPORT
           POS1 - LOCATION
           CIT5 - CITY
           CIT4 - CITY
           CIT3 - CITY
           CIT2 - CITY
           CIT1 - CITY
           TRU5 - TRUCK
           TRU4 - TRUCK
           TRU3 - TRUCK
           TRU2 - TRUCK
           TRU1 - TRUCK
           OBJ53 - PACKAGE
           OBJ52 - PACKAGE
           OBJ51 - PACKAGE
           OBJ43 - PACKAGE
           OBJ42 - PACKAGE
           OBJ41 - PACKAGE
           OBJ33 - PACKAGE
           OBJ32 - PACKAGE
           OBJ31 - PACKAGE
           OBJ23 - PACKAGE
           OBJ22 - PACKAGE
           OBJ21 - PACKAGE
           OBJ13 - PACKAGE
           OBJ12 - PACKAGE
           OBJ11 - PACKAGE)

 (:INIT
  (LOCATION APT1)
  (LOCATION APT2)
  (LOCATION APT3)
  (LOCATION APT4)
  (LOCATION APT5)
  (AT APN1 APT2)
  (AT APN2 APT2)
  (AT TRU1 POS1)
  (AT OBJ11 POS1)
  (AT OBJ12 POS1)
  (AT OBJ13 POS1)
  (AT TRU2 POS2)
  (AT OBJ21 POS2)
  (AT OBJ22 POS2)
  (AT OBJ23 POS2)
  (AT TRU3 POS3)
  (AT OBJ31 POS3)
  (AT OBJ32 POS3)
  (AT OBJ33 POS3)
  (AT TRU4 POS4)
  (AT OBJ41 POS4)
  (AT OBJ42 POS4)
  (AT OBJ43 POS4)
  (AT TRU5 POS5)
  (AT OBJ51 POS5)
  (AT OBJ52 POS5)
  (AT OBJ53 POS5)
  (IN-CITY POS1 CIT1)
  (IN-CITY APT1 CIT1)
  (IN-CITY POS2 CIT2)
  (IN-CITY APT2 CIT2)
  (IN-CITY POS3 CIT3)
  (IN-CITY APT3 CIT3)
  (IN-CITY POS4 CIT4)
  (IN-CITY APT4 CIT4)
  (IN-CITY POS5 CIT5)
  (IN-CITY APT5 CIT5))
 (:GOAL
  (AND (AT OBJ51 APT5)
       (AT OBJ53 APT5)
       (AT OBJ23 POS2)
       (AT OBJ31 POS5)
       (AT OBJ12 APT3)
       (AT OBJ32 POS4)
       (AT OBJ13 APT1)
       (AT OBJ42 POS4)
       (AT OBJ41 APT3)
       (AT OBJ11 APT4)
       (AT OBJ22 POS4)
       (AT OBJ43 APT5)
       (AT OBJ33 POS3)
       (AT OBJ21 POS5))))