(DEFINE (PROBLEM MIXED-F4-P2-U0-V0-G0-A0-N0-A0-B0-N0-F0-R0)
 (:DOMAIN MICONIC)
 (:OBJECTS P0 - PASSENGER
           P1 - PASSENGER
           F0 - FLOOR
           F1 - FLOOR
           F2 - FLOOR
           F3 - FLOOR)

 (:INIT
  (ABOVE F0 F1)
  (ABOVE F0 F2)
  (ABOVE F0 F3)
  (ABOVE F1 F2)
  (ABOVE F1 F3)
  (ABOVE F2 F3)
  (ORIGIN P0 F3)
  (DESTIN P0 F2)
  (ORIGIN P1 F1)
  (DESTIN P1 F3)
  (LIFT-AT F0))
 (:GOAL
  (AND (SERVED P0)
       (SERVED P1))))