(DEFINE (PROBLEM DEPOTPROB5656)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           CRATE10 - SURFACE
           CRATE11 - SURFACE
           CRATE12 - SURFACE
           CRATE13 - SURFACE
           CRATE14 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE11)
  (PALLET PALLET1)
  (AT PALLET1 DISTRIBUTOR0)
  (CLEAR CRATE14)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR1)
  (CLEAR CRATE10)
  (AT TRUCK0 DISTRIBUTOR1)
  (AT TRUCK1 DEPOT0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DISTRIBUTOR0)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR1)
  (AVAILABLE HOIST2)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR1)
  (ON CRATE0 PALLET2)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET0)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR1)
  (ON CRATE2 CRATE0)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR0)
  (ON CRATE3 PALLET1)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR0)
  (ON CRATE4 CRATE3)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR1)
  (ON CRATE5 CRATE2)
  (CRATE CRATE6)
  (AT CRATE6 DEPOT0)
  (ON CRATE6 CRATE1)
  (CRATE CRATE7)
  (AT CRATE7 DISTRIBUTOR0)
  (ON CRATE7 CRATE4)
  (CRATE CRATE8)
  (AT CRATE8 DISTRIBUTOR0)
  (ON CRATE8 CRATE7)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR0)
  (ON CRATE9 CRATE8)
  (CRATE CRATE10)
  (AT CRATE10 DISTRIBUTOR1)
  (ON CRATE10 CRATE5)
  (CRATE CRATE11)
  (AT CRATE11 DEPOT0)
  (ON CRATE11 CRATE6)
  (CRATE CRATE12)
  (AT CRATE12 DISTRIBUTOR0)
  (ON CRATE12 CRATE9)
  (CRATE CRATE13)
  (AT CRATE13 DISTRIBUTOR0)
  (ON CRATE13 CRATE12)
  (CRATE CRATE14)
  (AT CRATE14 DISTRIBUTOR0)
  (ON CRATE14 CRATE13))
 (:GOAL
  (AND (ON CRATE0 CRATE8)
       (ON CRATE1 CRATE9)
       (ON CRATE2 CRATE1)
       (ON CRATE3 CRATE12)
       (ON CRATE4 CRATE11)
       (ON CRATE5 CRATE0)
       (ON CRATE8 PALLET0)
       (ON CRATE9 PALLET1)
       (ON CRATE10 CRATE4)
       (ON CRATE11 CRATE5)
       (ON CRATE12 PALLET2))))