(DEFINE (PROBLEM DEPOTPROB1234)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE5)
  (PALLET PALLET1)
  (AT PALLET1 DISTRIBUTOR0)
  (CLEAR PALLET1)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR1)
  (CLEAR CRATE3)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR0)
  (CLEAR PALLET3)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR0)
  (CLEAR CRATE4)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR1)
  (CLEAR CRATE1)
  (AT TRUCK0 DISTRIBUTOR1)
  (AT TRUCK1 DEPOT0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DISTRIBUTOR0)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR1)
  (AVAILABLE HOIST2)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR0)
  (ON CRATE0 PALLET4)
  (CRATE CRATE1)
  (AT CRATE1 DISTRIBUTOR1)
  (ON CRATE1 PALLET5)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR1)
  (ON CRATE2 PALLET2)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR1)
  (ON CRATE3 CRATE2)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR0)
  (ON CRATE4 CRATE0)
  (CRATE CRATE5)
  (AT CRATE5 DEPOT0)
  (ON CRATE5 PALLET0))
 (:GOAL
  (AND (ON CRATE0 PALLET3)
       (ON CRATE1 CRATE4)
       (ON CRATE3 PALLET1)
       (ON CRATE4 PALLET5)
       (ON CRATE5 CRATE1))))