(DEFINE (PROBLEM DEPOTPROB4321)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE2)
  (PALLET PALLET1)
  (AT PALLET1 DISTRIBUTOR0)
  (CLEAR CRATE6)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR1)
  (CLEAR CRATE9)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR1)
  (CLEAR CRATE7)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR0)
  (CLEAR CRATE0)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR0)
  (CLEAR CRATE8)
  (AT TRUCK0 DISTRIBUTOR0)
  (AT TRUCK1 DISTRIBUTOR0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DISTRIBUTOR0)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR1)
  (AVAILABLE HOIST2)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR0)
  (ON CRATE0 PALLET4)
  (CRATE CRATE1)
  (AT CRATE1 DISTRIBUTOR0)
  (ON CRATE1 PALLET1)
  (CRATE CRATE2)
  (AT CRATE2 DEPOT0)
  (ON CRATE2 PALLET0)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR0)
  (ON CRATE3 PALLET5)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR1)
  (ON CRATE4 PALLET3)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR0)
  (ON CRATE5 CRATE1)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR0)
  (ON CRATE6 CRATE5)
  (CRATE CRATE7)
  (AT CRATE7 DISTRIBUTOR1)
  (ON CRATE7 CRATE4)
  (CRATE CRATE8)
  (AT CRATE8 DISTRIBUTOR0)
  (ON CRATE8 CRATE3)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR1)
  (ON CRATE9 PALLET2))
 (:GOAL
  (AND (ON CRATE0 PALLET3)
       (ON CRATE1 CRATE0)
       (ON CRATE3 CRATE8)
       (ON CRATE6 PALLET2)
       (ON CRATE7 PALLET1)
       (ON CRATE8 PALLET4)
       (ON CRATE9 PALLET0))))