(DEFINE (PROBLEM DEPOTPROB5451)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           CRATE10 - SURFACE
           CRATE11 - SURFACE
           CRATE12 - SURFACE
           CRATE13 - SURFACE
           CRATE14 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE2)
  (PALLET PALLET1)
  (AT PALLET1 DISTRIBUTOR0)
  (CLEAR CRATE14)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR1)
  (CLEAR CRATE13)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR1)
  (CLEAR CRATE10)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR0)
  (CLEAR CRATE12)
  (PALLET PALLET5)
  (AT PALLET5 DEPOT0)
  (CLEAR CRATE8)
  (AT TRUCK0 DISTRIBUTOR0)
  (AT TRUCK1 DISTRIBUTOR0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DISTRIBUTOR0)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR1)
  (AVAILABLE HOIST2)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR1)
  (ON CRATE0 PALLET2)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET0)
  (CRATE CRATE2)
  (AT CRATE2 DEPOT0)
  (ON CRATE2 CRATE1)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR0)
  (ON CRATE3 PALLET1)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR1)
  (ON CRATE4 CRATE0)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR1)
  (ON CRATE5 PALLET3)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR0)
  (ON CRATE6 CRATE3)
  (CRATE CRATE7)
  (AT CRATE7 DISTRIBUTOR0)
  (ON CRATE7 CRATE6)
  (CRATE CRATE8)
  (AT CRATE8 DEPOT0)
  (ON CRATE8 PALLET5)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR0)
  (ON CRATE9 CRATE7)
  (CRATE CRATE10)
  (AT CRATE10 DISTRIBUTOR1)
  (ON CRATE10 CRATE5)
  (CRATE CRATE11)
  (AT CRATE11 DISTRIBUTOR0)
  (ON CRATE11 PALLET4)
  (CRATE CRATE12)
  (AT CRATE12 DISTRIBUTOR0)
  (ON CRATE12 CRATE11)
  (CRATE CRATE13)
  (AT CRATE13 DISTRIBUTOR1)
  (ON CRATE13 CRATE4)
  (CRATE CRATE14)
  (AT CRATE14 DISTRIBUTOR0)
  (ON CRATE14 CRATE9))
 (:GOAL
  (AND (ON CRATE0 CRATE5)
       (ON CRATE1 CRATE2)
       (ON CRATE2 CRATE10)
       (ON CRATE3 PALLET0)
       (ON CRATE4 CRATE6)
       (ON CRATE5 PALLET5)
       (ON CRATE6 PALLET4)
       (ON CRATE9 CRATE1)
       (ON CRATE10 PALLET2)
       (ON CRATE11 PALLET1)
       (ON CRATE12 CRATE14)
       (ON CRATE13 CRATE3)
       (ON CRATE14 PALLET3))))