(DEFINE (PROBLEM DEPOTPROB7654)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DEPOT2 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           DISTRIBUTOR2 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE1)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE0)
  (PALLET PALLET2)
  (AT PALLET2 DEPOT2)
  (CLEAR CRATE4)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR0)
  (CLEAR CRATE5)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR1)
  (CLEAR PALLET4)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR2)
  (CLEAR CRATE3)
  (AT TRUCK0 DEPOT1)
  (AT TRUCK1 DEPOT2)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DEPOT2)
  (AVAILABLE HOIST2)
  (AT HOIST3 DISTRIBUTOR0)
  (AVAILABLE HOIST3)
  (AT HOIST4 DISTRIBUTOR1)
  (AVAILABLE HOIST4)
  (AT HOIST5 DISTRIBUTOR2)
  (AVAILABLE HOIST5)
  (CRATE CRATE0)
  (AT CRATE0 DEPOT1)
  (ON CRATE0 PALLET1)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET0)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR2)
  (ON CRATE2 PALLET5)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR2)
  (ON CRATE3 CRATE2)
  (CRATE CRATE4)
  (AT CRATE4 DEPOT2)
  (ON CRATE4 PALLET2)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR0)
  (ON CRATE5 PALLET3))
 (:GOAL
  (AND (ON CRATE0 CRATE4)
       (ON CRATE2 PALLET3)
       (ON CRATE3 PALLET0)
       (ON CRATE4 PALLET5))))