(DEFINE (PROBLEM DEPOTPROB7654)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DEPOT2 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           DISTRIBUTOR2 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           PALLET8 - SURFACE
           PALLET9 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE4)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE8)
  (PALLET PALLET2)
  (AT PALLET2 DEPOT2)
  (CLEAR PALLET2)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR0)
  (CLEAR CRATE9)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR1)
  (CLEAR CRATE7)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR2)
  (CLEAR PALLET5)
  (PALLET PALLET6)
  (AT PALLET6 DISTRIBUTOR2)
  (CLEAR CRATE3)
  (PALLET PALLET7)
  (AT PALLET7 DEPOT1)
  (CLEAR PALLET7)
  (PALLET PALLET8)
  (AT PALLET8 DISTRIBUTOR1)
  (CLEAR CRATE0)
  (PALLET PALLET9)
  (AT PALLET9 DEPOT0)
  (CLEAR CRATE5)
  (AT TRUCK0 DEPOT1)
  (AT TRUCK1 DEPOT2)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DEPOT2)
  (AVAILABLE HOIST2)
  (AT HOIST3 DISTRIBUTOR0)
  (AVAILABLE HOIST3)
  (AT HOIST4 DISTRIBUTOR1)
  (AVAILABLE HOIST4)
  (AT HOIST5 DISTRIBUTOR2)
  (AVAILABLE HOIST5)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR1)
  (ON CRATE0 PALLET8)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET9)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR0)
  (ON CRATE2 PALLET3)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR2)
  (ON CRATE3 PALLET6)
  (CRATE CRATE4)
  (AT CRATE4 DEPOT0)
  (ON CRATE4 PALLET0)
  (CRATE CRATE5)
  (AT CRATE5 DEPOT0)
  (ON CRATE5 CRATE1)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR1)
  (ON CRATE6 PALLET4)
  (CRATE CRATE7)
  (AT CRATE7 DISTRIBUTOR1)
  (ON CRATE7 CRATE6)
  (CRATE CRATE8)
  (AT CRATE8 DEPOT1)
  (ON CRATE8 PALLET1)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR0)
  (ON CRATE9 CRATE2))
 (:GOAL
  (AND (ON CRATE1 PALLET8)
       (ON CRATE2 PALLET3)
       (ON CRATE4 PALLET0)
       (ON CRATE5 PALLET5)
       (ON CRATE6 PALLET1)
       (ON CRATE7 CRATE6)
       (ON CRATE9 CRATE7))))