(DEFINE (PROBLEM DEPOTPROB4398)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE5)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE3)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR0)
  (CLEAR CRATE4)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR1)
  (CLEAR PALLET3)
  (PALLET PALLET4)
  (AT PALLET4 DEPOT1)
  (CLEAR CRATE0)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR1)
  (CLEAR PALLET5)
  (PALLET PALLET6)
  (AT PALLET6 DEPOT1)
  (CLEAR PALLET6)
  (PALLET PALLET7)
  (AT PALLET7 DISTRIBUTOR0)
  (CLEAR PALLET7)
  (AT TRUCK0 DEPOT1)
  (AT TRUCK1 DEPOT1)
  (AT TRUCK2 DEPOT0)
  (AT TRUCK3 DISTRIBUTOR1)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR0)
  (AVAILABLE HOIST2)
  (AT HOIST3 DISTRIBUTOR1)
  (AVAILABLE HOIST3)
  (AT HOIST4 DISTRIBUTOR1)
  (AVAILABLE HOIST4)
  (AT HOIST5 DEPOT1)
  (AVAILABLE HOIST5)
  (AT HOIST6 DEPOT1)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR1)
  (AVAILABLE HOIST7)
  (CRATE CRATE0)
  (AT CRATE0 DEPOT1)
  (ON CRATE0 PALLET4)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT1)
  (ON CRATE1 PALLET1)
  (CRATE CRATE2)
  (AT CRATE2 DEPOT0)
  (ON CRATE2 PALLET0)
  (CRATE CRATE3)
  (AT CRATE3 DEPOT1)
  (ON CRATE3 CRATE1)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR0)
  (ON CRATE4 PALLET2)
  (CRATE CRATE5)
  (AT CRATE5 DEPOT0)
  (ON CRATE5 CRATE2))
 (:GOAL
  (AND (ON CRATE0 PALLET3)
       (ON CRATE2 PALLET1)
       (ON CRATE3 PALLET0)
       (ON CRATE4 CRATE3)
       (ON CRATE5 PALLET2))))