(DEFINE (PROBLEM DEPOTPROB6587)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR PALLET0)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE4)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR0)
  (CLEAR CRATE9)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR1)
  (CLEAR CRATE7)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR0)
  (CLEAR CRATE2)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR1)
  (CLEAR CRATE1)
  (PALLET PALLET6)
  (AT PALLET6 DEPOT0)
  (CLEAR CRATE3)
  (PALLET PALLET7)
  (AT PALLET7 DISTRIBUTOR1)
  (CLEAR CRATE8)
  (AT TRUCK0 DEPOT1)
  (AT TRUCK1 DISTRIBUTOR1)
  (AT TRUCK2 DEPOT1)
  (AT TRUCK3 DEPOT0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR0)
  (AVAILABLE HOIST2)
  (AT HOIST3 DISTRIBUTOR1)
  (AVAILABLE HOIST3)
  (AT HOIST4 DEPOT0)
  (AVAILABLE HOIST4)
  (AT HOIST5 DEPOT0)
  (AVAILABLE HOIST5)
  (AT HOIST6 DEPOT0)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR1)
  (AVAILABLE HOIST7)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR1)
  (ON CRATE0 PALLET3)
  (CRATE CRATE1)
  (AT CRATE1 DISTRIBUTOR1)
  (ON CRATE1 PALLET5)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR0)
  (ON CRATE2 PALLET4)
  (CRATE CRATE3)
  (AT CRATE3 DEPOT0)
  (ON CRATE3 PALLET6)
  (CRATE CRATE4)
  (AT CRATE4 DEPOT1)
  (ON CRATE4 PALLET1)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR1)
  (ON CRATE5 CRATE0)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR1)
  (ON CRATE6 PALLET7)
  (CRATE CRATE7)
  (AT CRATE7 DISTRIBUTOR1)
  (ON CRATE7 CRATE5)
  (CRATE CRATE8)
  (AT CRATE8 DISTRIBUTOR1)
  (ON CRATE8 CRATE6)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR0)
  (ON CRATE9 PALLET2))
 (:GOAL
  (AND (ON CRATE1 PALLET7)
       (ON CRATE2 PALLET4)
       (ON CRATE3 CRATE8)
       (ON CRATE4 PALLET0)
       (ON CRATE6 PALLET1)
       (ON CRATE7 CRATE3)
       (ON CRATE8 PALLET6))))