(DEFINE (PROBLEM DEPOTPROB1916)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           CRATE10 - SURFACE
           CRATE11 - SURFACE
           CRATE12 - SURFACE
           CRATE13 - SURFACE
           CRATE14 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE13)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE11)
  (PALLET PALLET2)
  (AT PALLET2 DISTRIBUTOR0)
  (CLEAR CRATE14)
  (PALLET PALLET3)
  (AT PALLET3 DISTRIBUTOR1)
  (CLEAR CRATE10)
  (PALLET PALLET4)
  (AT PALLET4 DEPOT0)
  (CLEAR PALLET4)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR0)
  (CLEAR CRATE8)
  (PALLET PALLET6)
  (AT PALLET6 DISTRIBUTOR1)
  (CLEAR CRATE3)
  (PALLET PALLET7)
  (AT PALLET7 DEPOT1)
  (CLEAR CRATE5)
  (AT TRUCK0 DEPOT1)
  (AT TRUCK1 DISTRIBUTOR0)
  (AT TRUCK2 DEPOT0)
  (AT TRUCK3 DEPOT1)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DISTRIBUTOR0)
  (AVAILABLE HOIST2)
  (AT HOIST3 DISTRIBUTOR1)
  (AVAILABLE HOIST3)
  (AT HOIST4 DISTRIBUTOR0)
  (AVAILABLE HOIST4)
  (AT HOIST5 DEPOT0)
  (AVAILABLE HOIST5)
  (AT HOIST6 DISTRIBUTOR0)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR1)
  (AVAILABLE HOIST7)
  (CRATE CRATE0)
  (AT CRATE0 DEPOT0)
  (ON CRATE0 PALLET0)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT1)
  (ON CRATE1 PALLET1)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR0)
  (ON CRATE2 PALLET2)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR1)
  (ON CRATE3 PALLET6)
  (CRATE CRATE4)
  (AT CRATE4 DEPOT0)
  (ON CRATE4 CRATE0)
  (CRATE CRATE5)
  (AT CRATE5 DEPOT1)
  (ON CRATE5 PALLET7)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR0)
  (ON CRATE6 PALLET5)
  (CRATE CRATE7)
  (AT CRATE7 DEPOT0)
  (ON CRATE7 CRATE4)
  (CRATE CRATE8)
  (AT CRATE8 DISTRIBUTOR0)
  (ON CRATE8 CRATE6)
  (CRATE CRATE9)
  (AT CRATE9 DISTRIBUTOR1)
  (ON CRATE9 PALLET3)
  (CRATE CRATE10)
  (AT CRATE10 DISTRIBUTOR1)
  (ON CRATE10 CRATE9)
  (CRATE CRATE11)
  (AT CRATE11 DEPOT1)
  (ON CRATE11 CRATE1)
  (CRATE CRATE12)
  (AT CRATE12 DISTRIBUTOR0)
  (ON CRATE12 CRATE2)
  (CRATE CRATE13)
  (AT CRATE13 DEPOT0)
  (ON CRATE13 CRATE7)
  (CRATE CRATE14)
  (AT CRATE14 DISTRIBUTOR0)
  (ON CRATE14 CRATE12))
 (:GOAL
  (AND (ON CRATE0 CRATE10)
       (ON CRATE1 PALLET6)
       (ON CRATE2 CRATE12)
       (ON CRATE4 PALLET4)
       (ON CRATE5 PALLET2)
       (ON CRATE6 PALLET7)
       (ON CRATE8 CRATE4)
       (ON CRATE9 CRATE1)
       (ON CRATE10 PALLET1)
       (ON CRATE11 PALLET5)
       (ON CRATE12 CRATE5)
       (ON CRATE13 PALLET3)
       (ON CRATE14 PALLET0))))