(DEFINE (PROBLEM DEPOTPROB6178)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DEPOT2 - PLACE
           DEPOT3 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           DISTRIBUTOR2 - PLACE
           DISTRIBUTOR3 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           PALLET8 - SURFACE
           PALLET9 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE6)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE1)
  (PALLET PALLET2)
  (AT PALLET2 DEPOT2)
  (CLEAR PALLET2)
  (PALLET PALLET3)
  (AT PALLET3 DEPOT3)
  (CLEAR CRATE7)
  (PALLET PALLET4)
  (AT PALLET4 DISTRIBUTOR0)
  (CLEAR CRATE2)
  (PALLET PALLET5)
  (AT PALLET5 DISTRIBUTOR1)
  (CLEAR CRATE5)
  (PALLET PALLET6)
  (AT PALLET6 DISTRIBUTOR2)
  (CLEAR PALLET6)
  (PALLET PALLET7)
  (AT PALLET7 DISTRIBUTOR3)
  (CLEAR PALLET7)
  (PALLET PALLET8)
  (AT PALLET8 DISTRIBUTOR2)
  (CLEAR CRATE4)
  (PALLET PALLET9)
  (AT PALLET9 DEPOT3)
  (CLEAR CRATE0)
  (AT TRUCK0 DEPOT0)
  (AT TRUCK1 DISTRIBUTOR0)
  (AT TRUCK2 DEPOT2)
  (AT TRUCK3 DISTRIBUTOR3)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DEPOT2)
  (AVAILABLE HOIST2)
  (AT HOIST3 DEPOT3)
  (AVAILABLE HOIST3)
  (AT HOIST4 DISTRIBUTOR0)
  (AVAILABLE HOIST4)
  (AT HOIST5 DISTRIBUTOR1)
  (AVAILABLE HOIST5)
  (AT HOIST6 DISTRIBUTOR2)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR3)
  (AVAILABLE HOIST7)
  (CRATE CRATE0)
  (AT CRATE0 DEPOT3)
  (ON CRATE0 PALLET9)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT1)
  (ON CRATE1 PALLET1)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR0)
  (ON CRATE2 PALLET4)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR1)
  (ON CRATE3 PALLET5)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR2)
  (ON CRATE4 PALLET8)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR1)
  (ON CRATE5 CRATE3)
  (CRATE CRATE6)
  (AT CRATE6 DEPOT0)
  (ON CRATE6 PALLET0)
  (CRATE CRATE7)
  (AT CRATE7 DEPOT3)
  (ON CRATE7 PALLET3))
 (:GOAL
  (AND (ON CRATE0 PALLET6)
       (ON CRATE1 PALLET8)
       (ON CRATE3 CRATE1)
       (ON CRATE4 PALLET5)
       (ON CRATE5 CRATE7)
       (ON CRATE6 PALLET4)
       (ON CRATE7 CRATE4))))