(DEFINE (PROBLEM DEPOTPROB8715)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DEPOT2 - PLACE
           DEPOT3 - PLACE
           DEPOT4 - PLACE
           DEPOT5 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           DISTRIBUTOR2 - PLACE
           DISTRIBUTOR3 - PLACE
           DISTRIBUTOR4 - PLACE
           DISTRIBUTOR5 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           TRUCK4 - TRUCK
           TRUCK5 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           PALLET8 - SURFACE
           PALLET9 - SURFACE
           PALLET10 - SURFACE
           PALLET11 - SURFACE
           PALLET12 - SURFACE
           PALLET13 - SURFACE
           PALLET14 - SURFACE
           PALLET15 - SURFACE
           PALLET16 - SURFACE
           PALLET17 - SURFACE
           PALLET18 - SURFACE
           PALLET19 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST
           HOIST8 - HOIST
           HOIST9 - HOIST
           HOIST10 - HOIST
           HOIST11 - HOIST
           HOIST12 - HOIST
           HOIST13 - HOIST
           HOIST14 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE1)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE5)
  (PALLET PALLET2)
  (AT PALLET2 DEPOT2)
  (CLEAR PALLET2)
  (PALLET PALLET3)
  (AT PALLET3 DEPOT3)
  (CLEAR PALLET3)
  (PALLET PALLET4)
  (AT PALLET4 DEPOT4)
  (CLEAR CRATE6)
  (PALLET PALLET5)
  (AT PALLET5 DEPOT5)
  (CLEAR PALLET5)
  (PALLET PALLET6)
  (AT PALLET6 DISTRIBUTOR0)
  (CLEAR PALLET6)
  (PALLET PALLET7)
  (AT PALLET7 DISTRIBUTOR1)
  (CLEAR CRATE8)
  (PALLET PALLET8)
  (AT PALLET8 DISTRIBUTOR2)
  (CLEAR CRATE4)
  (PALLET PALLET9)
  (AT PALLET9 DISTRIBUTOR3)
  (CLEAR PALLET9)
  (PALLET PALLET10)
  (AT PALLET10 DISTRIBUTOR4)
  (CLEAR PALLET10)
  (PALLET PALLET11)
  (AT PALLET11 DISTRIBUTOR5)
  (CLEAR PALLET11)
  (PALLET PALLET12)
  (AT PALLET12 DISTRIBUTOR1)
  (CLEAR PALLET12)
  (PALLET PALLET13)
  (AT PALLET13 DISTRIBUTOR5)
  (CLEAR CRATE2)
  (PALLET PALLET14)
  (AT PALLET14 DEPOT2)
  (CLEAR PALLET14)
  (PALLET PALLET15)
  (AT PALLET15 DEPOT1)
  (CLEAR CRATE3)
  (PALLET PALLET16)
  (AT PALLET16 DEPOT1)
  (CLEAR CRATE0)
  (PALLET PALLET17)
  (AT PALLET17 DISTRIBUTOR2)
  (CLEAR PALLET17)
  (PALLET PALLET18)
  (AT PALLET18 DEPOT4)
  (CLEAR CRATE7)
  (PALLET PALLET19)
  (AT PALLET19 DEPOT1)
  (CLEAR CRATE9)
  (AT TRUCK0 DISTRIBUTOR2)
  (AT TRUCK1 DEPOT0)
  (AT TRUCK2 DISTRIBUTOR3)
  (AT TRUCK3 DISTRIBUTOR0)
  (AT TRUCK4 DEPOT0)
  (AT TRUCK5 DEPOT4)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DEPOT2)
  (AVAILABLE HOIST2)
  (AT HOIST3 DEPOT3)
  (AVAILABLE HOIST3)
  (AT HOIST4 DEPOT4)
  (AVAILABLE HOIST4)
  (AT HOIST5 DEPOT5)
  (AVAILABLE HOIST5)
  (AT HOIST6 DISTRIBUTOR0)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR1)
  (AVAILABLE HOIST7)
  (AT HOIST8 DISTRIBUTOR2)
  (AVAILABLE HOIST8)
  (AT HOIST9 DISTRIBUTOR3)
  (AVAILABLE HOIST9)
  (AT HOIST10 DISTRIBUTOR4)
  (AVAILABLE HOIST10)
  (AT HOIST11 DISTRIBUTOR5)
  (AVAILABLE HOIST11)
  (AT HOIST12 DEPOT5)
  (AVAILABLE HOIST12)
  (AT HOIST13 DEPOT1)
  (AVAILABLE HOIST13)
  (AT HOIST14 DEPOT4)
  (AVAILABLE HOIST14)
  (CRATE CRATE0)
  (AT CRATE0 DEPOT1)
  (ON CRATE0 PALLET16)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET0)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR5)
  (ON CRATE2 PALLET13)
  (CRATE CRATE3)
  (AT CRATE3 DEPOT1)
  (ON CRATE3 PALLET15)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR2)
  (ON CRATE4 PALLET8)
  (CRATE CRATE5)
  (AT CRATE5 DEPOT1)
  (ON CRATE5 PALLET1)
  (CRATE CRATE6)
  (AT CRATE6 DEPOT4)
  (ON CRATE6 PALLET4)
  (CRATE CRATE7)
  (AT CRATE7 DEPOT4)
  (ON CRATE7 PALLET18)
  (CRATE CRATE8)
  (AT CRATE8 DISTRIBUTOR1)
  (ON CRATE8 PALLET7)
  (CRATE CRATE9)
  (AT CRATE9 DEPOT1)
  (ON CRATE9 PALLET19))
 (:GOAL
  (AND (ON CRATE0 PALLET2)
       (ON CRATE1 PALLET7)
       (ON CRATE2 PALLET11)
       (ON CRATE3 PALLET3)
       (ON CRATE5 PALLET5)
       (ON CRATE6 PALLET12)
       (ON CRATE7 PALLET18)
       (ON CRATE8 PALLET15))))