(DEFINE (PROBLEM DEPOTPROB1817)
 (:DOMAIN DEPOT)
 (:OBJECTS DEPOT0 - PLACE
           DEPOT1 - PLACE
           DEPOT2 - PLACE
           DEPOT3 - PLACE
           DEPOT4 - PLACE
           DEPOT5 - PLACE
           DISTRIBUTOR0 - PLACE
           DISTRIBUTOR1 - PLACE
           DISTRIBUTOR2 - PLACE
           DISTRIBUTOR3 - PLACE
           DISTRIBUTOR4 - PLACE
           DISTRIBUTOR5 - PLACE
           TRUCK0 - TRUCK
           TRUCK1 - TRUCK
           TRUCK2 - TRUCK
           TRUCK3 - TRUCK
           TRUCK4 - TRUCK
           TRUCK5 - TRUCK
           PALLET0 - SURFACE
           PALLET1 - SURFACE
           PALLET2 - SURFACE
           PALLET3 - SURFACE
           PALLET4 - SURFACE
           PALLET5 - SURFACE
           PALLET6 - SURFACE
           PALLET7 - SURFACE
           PALLET8 - SURFACE
           PALLET9 - SURFACE
           PALLET10 - SURFACE
           PALLET11 - SURFACE
           PALLET12 - SURFACE
           PALLET13 - SURFACE
           PALLET14 - SURFACE
           PALLET15 - SURFACE
           PALLET16 - SURFACE
           PALLET17 - SURFACE
           PALLET18 - SURFACE
           PALLET19 - SURFACE
           CRATE0 - SURFACE
           CRATE1 - SURFACE
           CRATE2 - SURFACE
           CRATE3 - SURFACE
           CRATE4 - SURFACE
           CRATE5 - SURFACE
           CRATE6 - SURFACE
           CRATE7 - SURFACE
           CRATE8 - SURFACE
           CRATE9 - SURFACE
           CRATE10 - SURFACE
           CRATE11 - SURFACE
           CRATE12 - SURFACE
           CRATE13 - SURFACE
           CRATE14 - SURFACE
           CRATE15 - SURFACE
           CRATE16 - SURFACE
           CRATE17 - SURFACE
           CRATE18 - SURFACE
           CRATE19 - SURFACE
           HOIST0 - HOIST
           HOIST1 - HOIST
           HOIST2 - HOIST
           HOIST3 - HOIST
           HOIST4 - HOIST
           HOIST5 - HOIST
           HOIST6 - HOIST
           HOIST7 - HOIST
           HOIST8 - HOIST
           HOIST9 - HOIST
           HOIST10 - HOIST
           HOIST11 - HOIST
           HOIST12 - HOIST
           HOIST13 - HOIST
           HOIST14 - HOIST)

 (:INIT
  (PALLET PALLET0)
  (AT PALLET0 DEPOT0)
  (CLEAR CRATE10)
  (PALLET PALLET1)
  (AT PALLET1 DEPOT1)
  (CLEAR CRATE17)
  (PALLET PALLET2)
  (AT PALLET2 DEPOT2)
  (CLEAR PALLET2)
  (PALLET PALLET3)
  (AT PALLET3 DEPOT3)
  (CLEAR PALLET3)
  (PALLET PALLET4)
  (AT PALLET4 DEPOT4)
  (CLEAR PALLET4)
  (PALLET PALLET5)
  (AT PALLET5 DEPOT5)
  (CLEAR CRATE8)
  (PALLET PALLET6)
  (AT PALLET6 DISTRIBUTOR0)
  (CLEAR PALLET6)
  (PALLET PALLET7)
  (AT PALLET7 DISTRIBUTOR1)
  (CLEAR CRATE19)
  (PALLET PALLET8)
  (AT PALLET8 DISTRIBUTOR2)
  (CLEAR CRATE13)
  (PALLET PALLET9)
  (AT PALLET9 DISTRIBUTOR3)
  (CLEAR CRATE16)
  (PALLET PALLET10)
  (AT PALLET10 DISTRIBUTOR4)
  (CLEAR CRATE14)
  (PALLET PALLET11)
  (AT PALLET11 DISTRIBUTOR5)
  (CLEAR CRATE0)
  (PALLET PALLET12)
  (AT PALLET12 DISTRIBUTOR4)
  (CLEAR CRATE18)
  (PALLET PALLET13)
  (AT PALLET13 DISTRIBUTOR2)
  (CLEAR CRATE15)
  (PALLET PALLET14)
  (AT PALLET14 DEPOT3)
  (CLEAR PALLET14)
  (PALLET PALLET15)
  (AT PALLET15 DEPOT3)
  (CLEAR PALLET15)
  (PALLET PALLET16)
  (AT PALLET16 DISTRIBUTOR1)
  (CLEAR PALLET16)
  (PALLET PALLET17)
  (AT PALLET17 DISTRIBUTOR2)
  (CLEAR CRATE6)
  (PALLET PALLET18)
  (AT PALLET18 DISTRIBUTOR3)
  (CLEAR PALLET18)
  (PALLET PALLET19)
  (AT PALLET19 DISTRIBUTOR1)
  (CLEAR PALLET19)
  (AT TRUCK0 DEPOT2)
  (AT TRUCK1 DISTRIBUTOR4)
  (AT TRUCK2 DISTRIBUTOR2)
  (AT TRUCK3 DEPOT0)
  (AT TRUCK4 DISTRIBUTOR3)
  (AT TRUCK5 DISTRIBUTOR0)
  (AT HOIST0 DEPOT0)
  (AVAILABLE HOIST0)
  (AT HOIST1 DEPOT1)
  (AVAILABLE HOIST1)
  (AT HOIST2 DEPOT2)
  (AVAILABLE HOIST2)
  (AT HOIST3 DEPOT3)
  (AVAILABLE HOIST3)
  (AT HOIST4 DEPOT4)
  (AVAILABLE HOIST4)
  (AT HOIST5 DEPOT5)
  (AVAILABLE HOIST5)
  (AT HOIST6 DISTRIBUTOR0)
  (AVAILABLE HOIST6)
  (AT HOIST7 DISTRIBUTOR1)
  (AVAILABLE HOIST7)
  (AT HOIST8 DISTRIBUTOR2)
  (AVAILABLE HOIST8)
  (AT HOIST9 DISTRIBUTOR3)
  (AVAILABLE HOIST9)
  (AT HOIST10 DISTRIBUTOR4)
  (AVAILABLE HOIST10)
  (AT HOIST11 DISTRIBUTOR5)
  (AVAILABLE HOIST11)
  (AT HOIST12 DEPOT0)
  (AVAILABLE HOIST12)
  (AT HOIST13 DEPOT5)
  (AVAILABLE HOIST13)
  (AT HOIST14 DEPOT5)
  (AVAILABLE HOIST14)
  (CRATE CRATE0)
  (AT CRATE0 DISTRIBUTOR5)
  (ON CRATE0 PALLET11)
  (CRATE CRATE1)
  (AT CRATE1 DEPOT0)
  (ON CRATE1 PALLET0)
  (CRATE CRATE2)
  (AT CRATE2 DISTRIBUTOR4)
  (ON CRATE2 PALLET10)
  (CRATE CRATE3)
  (AT CRATE3 DISTRIBUTOR2)
  (ON CRATE3 PALLET8)
  (CRATE CRATE4)
  (AT CRATE4 DISTRIBUTOR1)
  (ON CRATE4 PALLET7)
  (CRATE CRATE5)
  (AT CRATE5 DISTRIBUTOR4)
  (ON CRATE5 CRATE2)
  (CRATE CRATE6)
  (AT CRATE6 DISTRIBUTOR2)
  (ON CRATE6 PALLET17)
  (CRATE CRATE7)
  (AT CRATE7 DEPOT5)
  (ON CRATE7 PALLET5)
  (CRATE CRATE8)
  (AT CRATE8 DEPOT5)
  (ON CRATE8 CRATE7)
  (CRATE CRATE9)
  (AT CRATE9 DEPOT0)
  (ON CRATE9 CRATE1)
  (CRATE CRATE10)
  (AT CRATE10 DEPOT0)
  (ON CRATE10 CRATE9)
  (CRATE CRATE11)
  (AT CRATE11 DISTRIBUTOR3)
  (ON CRATE11 PALLET9)
  (CRATE CRATE12)
  (AT CRATE12 DEPOT1)
  (ON CRATE12 PALLET1)
  (CRATE CRATE13)
  (AT CRATE13 DISTRIBUTOR2)
  (ON CRATE13 CRATE3)
  (CRATE CRATE14)
  (AT CRATE14 DISTRIBUTOR4)
  (ON CRATE14 CRATE5)
  (CRATE CRATE15)
  (AT CRATE15 DISTRIBUTOR2)
  (ON CRATE15 PALLET13)
  (CRATE CRATE16)
  (AT CRATE16 DISTRIBUTOR3)
  (ON CRATE16 CRATE11)
  (CRATE CRATE17)
  (AT CRATE17 DEPOT1)
  (ON CRATE17 CRATE12)
  (CRATE CRATE18)
  (AT CRATE18 DISTRIBUTOR4)
  (ON CRATE18 PALLET12)
  (CRATE CRATE19)
  (AT CRATE19 DISTRIBUTOR1)
  (ON CRATE19 CRATE4))
 (:GOAL
  (AND (ON CRATE0 PALLET14)
       (ON CRATE1 PALLET15)
       (ON CRATE2 PALLET13)
       (ON CRATE3 PALLET18)
       (ON CRATE5 PALLET12)
       (ON CRATE6 PALLET6)
       (ON CRATE7 PALLET5)
       (ON CRATE8 CRATE10)
       (ON CRATE9 PALLET17)
       (ON CRATE10 CRATE17)
       (ON CRATE11 PALLET1)
       (ON CRATE12 PALLET16)
       (ON CRATE13 CRATE16)
       (ON CRATE15 PALLET7)
       (ON CRATE16 CRATE15)
       (ON CRATE17 PALLET2)
       (ON CRATE18 PALLET4)
       (ON CRATE19 PALLET9))))