(DEFINE (PROBLEM STRIPS-MYSTY-X-1)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS RICE - FOOD
           PEAR - FOOD
           FLOUNDER - FOOD
           OKRA - FOOD
           PORK - FOOD
           LAMB - FOOD
           REST - PLEASURE
           HANGOVER - PAIN
           DEPRESSION - PAIN
           ABRASION - PAIN
           KENTUCKY - OBJECT
           BOSNIA - OBJECT
           SURREY - OBJECT
           PENNSYLVANIA - OBJECT
           ALSACE - OBJECT
           QUEBEC - OBJECT
           GUANABARA - OBJECT
           MARS - PLANET
           EARTH - PLANET
           URANUS - PLANET
           VENUS - PLANET)

 (:INIT
  (PROVINCE KENTUCKY)
  (PROVINCE BOSNIA)
  (PROVINCE SURREY)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE ALSACE)
  (PROVINCE QUEBEC)
  (PROVINCE GUANABARA)
  (EATS LAMB PORK)
  (EATS PORK OKRA)
  (LOCALE OKRA GUANABARA)
  (LOCALE PORK QUEBEC)
  (EATS PORK LAMB)
  (HARMONY REST VENUS)
  (EATS LAMB FLOUNDER)
  (CRAVES DEPRESSION FLOUNDER)
  (EATS OKRA PEAR)
  (EATS RICE RICE)
  (EATS RICE FLOUNDER)
  (ATTACKS KENTUCKY BOSNIA)
  (ATTACKS PENNSYLVANIA ALSACE)
  (ATTACKS ALSACE QUEBEC)
  (CRAVES ABRASION PORK)
  (LOCALE RICE BOSNIA)
  (ORBITS MARS EARTH)
  (EATS FLOUNDER LAMB)
  (CRAVES REST PORK)
  (ORBITS EARTH URANUS)
  (LOCALE PEAR SURREY)
  (CRAVES HANGOVER RICE)
  (ATTACKS BOSNIA SURREY)
  (ATTACKS SURREY PENNSYLVANIA)
  (LOCALE LAMB PENNSYLVANIA)
  (EATS FLOUNDER RICE)
  (EATS RICE PEAR)
  (ATTACKS QUEBEC GUANABARA)
  (EATS PEAR OKRA)
  (EATS PEAR RICE)
  (EATS OKRA PORK)
  (ORBITS URANUS VENUS)
  (LOCALE FLOUNDER ALSACE))
 (:GOAL (AND (CRAVES ABRASION RICE))))