(DEFINE (PROBLEM STRIPS-MYSTY-X-28)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS WURST - FOOD
           SHRIMP - FOOD
           MUFFIN - FOOD
           BROCCOLI - FOOD
           LAMB - FOOD
           INTOXICATION - PLEASURE
           LONELINESS - PAIN
           ANXIETY - PAIN
           HANGOVER - PAIN
           ANGER - PAIN
           ANGINA - PAIN
           BOILS - PAIN
           GRIEF - PAIN
           GOIAS - OBJECT
           BOSNIA - OBJECT
           PENNSYLVANIA - OBJECT
           MORAVIA - OBJECT
           QUEBEC - OBJECT
           OREGON - OBJECT
           ALSACE - OBJECT
           KENTUCKY - OBJECT
           NEPTUNE - PLANET
           VULCAN - PLANET
           EARTH - PLANET)

 (:INIT
  (PROVINCE GOIAS)
  (PROVINCE BOSNIA)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE MORAVIA)
  (PROVINCE QUEBEC)
  (PROVINCE OREGON)
  (PROVINCE ALSACE)
  (PROVINCE KENTUCKY)
  (CRAVES HANGOVER SHRIMP)
  (ATTACKS MORAVIA QUEBEC)
  (CRAVES ANGER MUFFIN)
  (EATS LAMB SHRIMP)
  (EATS SHRIMP WURST)
  (EATS WURST MUFFIN)
  (CRAVES INTOXICATION WURST)
  (ATTACKS GOIAS BOSNIA)
  (EATS BROCCOLI LAMB)
  (EATS WURST LAMB)
  (EATS MUFFIN WURST)
  (CRAVES BOILS BROCCOLI)
  (LOCALE SHRIMP ALSACE)
  (ATTACKS QUEBEC OREGON)
  (EATS BROCCOLI MUFFIN)
  (LOCALE LAMB KENTUCKY)
  (ATTACKS ALSACE KENTUCKY)
  (EATS SHRIMP LAMB)
  (ORBITS VULCAN EARTH)
  (CRAVES ANXIETY SHRIMP)
  (LOCALE BROCCOLI KENTUCKY)
  (HARMONY INTOXICATION EARTH)
  (CRAVES GRIEF LAMB)
  (LOCALE WURST BOSNIA)
  (ORBITS NEPTUNE VULCAN)
  (EATS WURST SHRIMP)
  (LOCALE MUFFIN PENNSYLVANIA)
  (ATTACKS PENNSYLVANIA MORAVIA)
  (EATS LAMB WURST)
  (ATTACKS OREGON ALSACE)
  (EATS LAMB BROCCOLI)
  (CRAVES ANGINA MUFFIN)
  (CRAVES LONELINESS WURST)
  (EATS MUFFIN BROCCOLI)
  (ATTACKS BOSNIA PENNSYLVANIA))
 (:GOAL
  (AND (CRAVES ANGER LAMB)
       (CRAVES BOILS LAMB))))