(DEFINE (PROBLEM STRIPS-MYSTY-X-11)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS PISTACHIO - FOOD
           BACON - FOOD
           PEAR - FOOD
           SWEETROLL - FOOD
           SHRIMP - FOOD
           CHICKEN - FOOD
           CHERRY - FOOD
           TOMATO - FOOD
           LUBRICITY - PLEASURE
           JEALOUSY - PAIN
           DREAD - PAIN
           LACERATION - PAIN
           LONELINESS - PAIN
           SCIATICA - PAIN
           HANGOVER - PAIN
           PROSTATITIS - PAIN
           BOILS - PAIN
           ALSACE - OBJECT
           QUEBEC - OBJECT
           BOSNIA - OBJECT
           SURREY - OBJECT
           MANITOBA - OBJECT
           KENTUCKY - OBJECT
           NEPTUNE - PLANET
           URANUS - PLANET
           SATURN - PLANET)

 (:INIT
  (PROVINCE ALSACE)
  (PROVINCE QUEBEC)
  (PROVINCE BOSNIA)
  (PROVINCE SURREY)
  (PROVINCE MANITOBA)
  (PROVINCE KENTUCKY)
  (CRAVES SCIATICA SHRIMP)
  (EATS PEAR CHERRY)
  (EATS BACON PISTACHIO)
  (LOCALE SHRIMP MANITOBA)
  (EATS PISTACHIO CHICKEN)
  (LOCALE SWEETROLL QUEBEC)
  (EATS SWEETROLL PEAR)
  (LOCALE PEAR BOSNIA)
  (LOCALE BACON ALSACE)
  (ATTACKS QUEBEC BOSNIA)
  (EATS TOMATO CHICKEN)
  (EATS CHERRY PEAR)
  (EATS SWEETROLL TOMATO)
  (EATS PISTACHIO BACON)
  (CRAVES LUBRICITY PEAR)
  (EATS CHICKEN PISTACHIO)
  (LOCALE TOMATO BOSNIA)
  (EATS TOMATO SHRIMP)
  (EATS BACON PEAR)
  (EATS PEAR SWEETROLL)
  (CRAVES DREAD BACON)
  (EATS SHRIMP CHICKEN)
  (ATTACKS ALSACE QUEBEC)
  (CRAVES JEALOUSY PISTACHIO)
  (EATS CHICKEN TOMATO)
  (ORBITS URANUS SATURN)
  (CRAVES BOILS TOMATO)
  (ATTACKS BOSNIA SURREY)
  (EATS TOMATO SWEETROLL)
  (LOCALE CHICKEN KENTUCKY)
  (CRAVES HANGOVER CHICKEN)
  (CRAVES LACERATION PEAR)
  (LOCALE CHERRY SURREY)
  (EATS SHRIMP TOMATO)
  (EATS PEAR BACON)
  (ATTACKS SURREY MANITOBA)
  (EATS CHERRY CHICKEN)
  (ORBITS NEPTUNE URANUS)
  (CRAVES LONELINESS SWEETROLL)
  (EATS CHICKEN CHERRY)
  (CRAVES PROSTATITIS CHERRY)
  (ATTACKS MANITOBA KENTUCKY)
  (EATS CHICKEN SHRIMP)
  (LOCALE PISTACHIO SURREY)
  (HARMONY LUBRICITY SATURN))
 (:GOAL
  (AND (CRAVES LACERATION SHRIMP)
       (CRAVES LONELINESS SHRIMP))))