(DEFINE (PROBLEM STRIPS-MYSTY-X-27)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS WURST - FOOD
           GUAVA - FOOD
           MUFFIN - FOOD
           PORK - FOOD
           ONION - FOOD
           POPOVER - FOOD
           SCALLION - FOOD
           TRIUMPH - PLEASURE
           LOVE - PLEASURE
           SATISFACTION - PLEASURE
           ABRASION - PAIN
           ANXIETY - PAIN
           DREAD - PAIN
           LONELINESS - PAIN
           GRIEF - PAIN
           BOILS - PAIN
           MORAVIA - OBJECT
           SURREY - OBJECT
           GUANABARA - OBJECT
           MANITOBA - OBJECT
           ARIZONA - OBJECT
           PENNSYLVANIA - OBJECT
           ALSACE - OBJECT
           QUEBEC - OBJECT
           KENTUCKY - OBJECT
           OREGON - OBJECT
           BAVARIA - OBJECT
           GOIAS - OBJECT
           BOSNIA - OBJECT
           MERCURY - PLANET
           MARS - PLANET
           URANUS - PLANET
           EARTH - PLANET)

 (:INIT
  (PROVINCE MORAVIA)
  (PROVINCE SURREY)
  (PROVINCE GUANABARA)
  (PROVINCE MANITOBA)
  (PROVINCE ARIZONA)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE ALSACE)
  (PROVINCE QUEBEC)
  (PROVINCE KENTUCKY)
  (PROVINCE OREGON)
  (PROVINCE BAVARIA)
  (PROVINCE GOIAS)
  (PROVINCE BOSNIA)
  (LOCALE WURST BAVARIA)
  (CRAVES ABRASION WURST)
  (ATTACKS KENTUCKY OREGON)
  (EATS WURST GUAVA)
  (EATS PORK MUFFIN)
  (ATTACKS GOIAS BOSNIA)
  (EATS SCALLION MUFFIN)
  (LOCALE ONION BOSNIA)
  (CRAVES ANXIETY WURST)
  (EATS SCALLION POPOVER)
  (CRAVES BOILS SCALLION)
  (HARMONY SATISFACTION URANUS)
  (EATS MUFFIN SCALLION)
  (LOCALE SCALLION PENNSYLVANIA)
  (EATS ONION WURST)
  (EATS SCALLION GUAVA)
  (ATTACKS QUEBEC KENTUCKY)
  (EATS MUFFIN PORK)
  (CRAVES TRIUMPH ONION)
  (EATS WURST ONION)
  (CRAVES DREAD WURST)
  (HARMONY LOVE URANUS)
  (ATTACKS OREGON BAVARIA)
  (ORBITS URANUS EARTH)
  (ATTACKS GUANABARA MANITOBA)
  (LOCALE POPOVER OREGON)
  (HARMONY TRIUMPH EARTH)
  (ATTACKS PENNSYLVANIA ALSACE)
  (ORBITS MERCURY MARS)
  (LOCALE GUAVA OREGON)
  (LOCALE MUFFIN GUANABARA)
  (ATTACKS MANITOBA ARIZONA)
  (EATS MUFFIN ONION)
  (CRAVES SATISFACTION SCALLION)
  (EATS POPOVER ONION)
  (EATS ONION MUFFIN)
  (EATS POPOVER SCALLION)
  (ATTACKS ALSACE QUEBEC)
  (EATS GUAVA SCALLION)
  (EATS ONION PORK)
  (ATTACKS BAVARIA GOIAS)
  (EATS GUAVA WURST)
  (ATTACKS SURREY GUANABARA)
  (EATS ONION POPOVER)
  (EATS PORK ONION)
  (ATTACKS ARIZONA PENNSYLVANIA)
  (CRAVES LOVE POPOVER)
  (CRAVES LONELINESS SCALLION)
  (LOCALE PORK PENNSYLVANIA)
  (CRAVES GRIEF SCALLION)
  (ORBITS MARS URANUS)
  (ATTACKS MORAVIA SURREY))
 (:GOAL
  (AND (CRAVES GRIEF GUAVA)
       (CRAVES BOILS GUAVA))))