(DEFINE (PROBLEM STRIPS-MYSTY-X-29)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS PAPAYA - FOOD
           SCALLOP - FOOD
           MELON - FOOD
           POPOVER - FOOD
           PEAR - FOOD
           SHRIMP - FOOD
           BROCCOLI - FOOD
           PORK - FOOD
           ACHIEVEMENT - PLEASURE
           EXCITEMENT - PLEASURE
           ABRASION - PAIN
           HANGOVER - PAIN
           ANGER - PAIN
           LACERATION - PAIN
           ANXIETY - PAIN
           ANGINA - PAIN
           GRIEF - PAIN
           PROSTATITIS - PAIN
           BOILS - PAIN
           SCIATICA - PAIN
           JEALOUSY - PAIN
           ARIZONA - OBJECT
           PENNSYLVANIA - OBJECT
           ALSACE - OBJECT
           QUEBEC - OBJECT
           MANITOBA - OBJECT
           BAVARIA - OBJECT
           OREGON - OBJECT
           KENTUCKY - OBJECT
           MORAVIA - OBJECT
           EARTH - PLANET
           PLUTO - PLANET
           NEPTUNE - PLANET
           URANUS - PLANET)

 (:INIT
  (PROVINCE ARIZONA)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE ALSACE)
  (PROVINCE QUEBEC)
  (PROVINCE MANITOBA)
  (PROVINCE BAVARIA)
  (PROVINCE OREGON)
  (PROVINCE KENTUCKY)
  (PROVINCE MORAVIA)
  (LOCALE SCALLOP OREGON)
  (LOCALE MELON MORAVIA)
  (EATS MELON SHRIMP)
  (CRAVES ANXIETY MELON)
  (EATS POPOVER SHRIMP)
  (CRAVES ACHIEVEMENT SCALLOP)
  (CRAVES EXCITEMENT PORK)
  (EATS SCALLOP PORK)
  (EATS MELON SCALLOP)
  (CRAVES ABRASION PAPAYA)
  (ATTACKS BAVARIA OREGON)
  (EATS SHRIMP MELON)
  (EATS BROCCOLI PORK)
  (ATTACKS ARIZONA PENNSYLVANIA)
  (EATS PORK SCALLOP)
  (ORBITS EARTH PLUTO)
  (LOCALE POPOVER BAVARIA)
  (EATS PEAR PAPAYA)
  (HARMONY EXCITEMENT URANUS)
  (EATS PAPAYA POPOVER)
  (CRAVES LACERATION MELON)
  (EATS POPOVER PAPAYA)
  (EATS PAPAYA PEAR)
  (ATTACKS MANITOBA BAVARIA)
  (CRAVES ANGINA MELON)
  (CRAVES BOILS BROCCOLI)
  (ATTACKS OREGON KENTUCKY)
  (EATS SHRIMP BROCCOLI)
  (CRAVES HANGOVER SCALLOP)
  (CRAVES GRIEF SHRIMP)
  (LOCALE PEAR ARIZONA)
  (EATS SHRIMP POPOVER)
  (CRAVES ANGER SCALLOP)
  (CRAVES SCIATICA PORK)
  (LOCALE PAPAYA QUEBEC)
  (ORBITS PLUTO NEPTUNE)
  (ATTACKS PENNSYLVANIA ALSACE)
  (EATS PORK PEAR)
  (ATTACKS QUEBEC MANITOBA)
  (CRAVES JEALOUSY PORK)
  (EATS PORK BROCCOLI)
  (EATS PEAR PORK)
  (ATTACKS ALSACE QUEBEC)
  (ORBITS NEPTUNE URANUS)
  (EATS SCALLOP MELON)
  (LOCALE BROCCOLI ALSACE)
  (LOCALE SHRIMP KENTUCKY)
  (CRAVES PROSTATITIS SHRIMP)
  (LOCALE PORK BAVARIA)
  (ATTACKS KENTUCKY MORAVIA)
  (HARMONY ACHIEVEMENT URANUS)
  (EATS BROCCOLI SHRIMP))
 (:GOAL
  (AND (CRAVES JEALOUSY SHRIMP)
       (CRAVES PROSTATITIS SHRIMP))))