(DEFINE (PROBLEM STRIPS-MYSTY-X-26)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS PEPPER - FOOD
           PAPAYA - FOOD
           FLOUNDER - FOOD
           ENDIVE - FOOD
           MARZIPAN - FOOD
           HAROSET - FOOD
           TURKEY - FOOD
           SCALLOP - FOOD
           PISTACHIO - FOOD
           SNICKERS - FOOD
           HAMBURGER - FOOD
           RICE - FOOD
           UNDERSTANDING - PLEASURE
           LEARNING - PLEASURE
           ENTERTAINMENT - PLEASURE
           EMPATHY - PLEASURE
           SATISFACTION - PLEASURE
           DEPRESSION - PAIN
           BOILS - PAIN
           HANGOVER - PAIN
           JEALOUSY - PAIN
           MORAVIA - OBJECT
           KENTUCKY - OBJECT
           QUEBEC - OBJECT
           MANITOBA - OBJECT
           OREGON - OBJECT
           BAVARIA - OBJECT
           EARTH - PLANET
           NEPTUNE - PLANET
           VENUS - PLANET
           SATURN - PLANET)

 (:INIT
  (PROVINCE MORAVIA)
  (PROVINCE KENTUCKY)
  (PROVINCE QUEBEC)
  (PROVINCE MANITOBA)
  (PROVINCE OREGON)
  (PROVINCE BAVARIA)
  (HARMONY SATISFACTION SATURN)
  (EATS HAROSET HAMBURGER)
  (CRAVES ENTERTAINMENT HAROSET)
  (EATS FLOUNDER PAPAYA)
  (EATS HAMBURGER HAROSET)
  (EATS RICE HAROSET)
  (EATS RICE SCALLOP)
  (LOCALE HAMBURGER BAVARIA)
  (EATS MARZIPAN HAROSET)
  (EATS ENDIVE HAROSET)
  (LOCALE PISTACHIO KENTUCKY)
  (EATS ENDIVE PISTACHIO)
  (EATS PEPPER SNICKERS)
  (EATS TURKEY MARZIPAN)
  (EATS HAROSET MARZIPAN)
  (ATTACKS MANITOBA OREGON)
  (HARMONY ENTERTAINMENT NEPTUNE)
  (EATS TURKEY PAPAYA)
  (LOCALE HAROSET BAVARIA)
  (EATS RICE PISTACHIO)
  (ATTACKS QUEBEC MANITOBA)
  (EATS HAMBURGER MARZIPAN)
  (ORBITS NEPTUNE VENUS)
  (EATS ENDIVE RICE)
  (EATS PEPPER FLOUNDER)
  (HARMONY UNDERSTANDING NEPTUNE)
  (EATS HAROSET ENDIVE)
  (EATS PAPAYA FLOUNDER)
  (EATS PISTACHIO RICE)
  (ATTACKS MORAVIA KENTUCKY)
  (LOCALE TURKEY OREGON)
  (LOCALE SCALLOP OREGON)
  (LOCALE SNICKERS KENTUCKY)
  (EATS PAPAYA TURKEY)
  (CRAVES SATISFACTION SNICKERS)
  (EATS HAROSET RICE)
  (EATS SCALLOP HAMBURGER)
  (LOCALE MARZIPAN MORAVIA)
  (ATTACKS OREGON BAVARIA)
  (EATS SCALLOP RICE)
  (LOCALE RICE OREGON)
  (CRAVES DEPRESSION MARZIPAN)
  (LOCALE ENDIVE KENTUCKY)
  (LOCALE PAPAYA KENTUCKY)
  (CRAVES HANGOVER PISTACHIO)
  (EATS MARZIPAN HAMBURGER)
  (EATS RICE ENDIVE)
  (CRAVES EMPATHY SCALLOP)
  (ATTACKS KENTUCKY QUEBEC)
  (CRAVES UNDERSTANDING PAPAYA)
  (EATS SNICKERS HAMBURGER)
  (CRAVES LEARNING MARZIPAN)
  (EATS HAMBURGER SCALLOP)
  (HARMONY EMPATHY VENUS)
  (EATS FLOUNDER PEPPER)
  (EATS PISTACHIO ENDIVE)
  (EATS PISTACHIO TURKEY)
  (CRAVES BOILS HAROSET)
  (CRAVES JEALOUSY SNICKERS)
  (ORBITS VENUS SATURN)
  (LOCALE PEPPER MORAVIA)
  (HARMONY LEARNING NEPTUNE)
  (EATS TURKEY PISTACHIO)
  (EATS SNICKERS PEPPER)
  (EATS HAMBURGER SNICKERS)
  (LOCALE FLOUNDER QUEBEC)
  (EATS MARZIPAN TURKEY)
  (ORBITS EARTH NEPTUNE))
 (:GOAL (AND (CRAVES BOILS PAPAYA))))