(DEFINE (PROBLEM STRIPS-MYSTY-X-30)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS TURKEY - FOOD
           CUCUMBER - FOOD
           BAGUETTE - FOOD
           BEEF - FOOD
           MUFFIN - FOOD
           HOTDOG - FOOD
           MUTTON - FOOD
           CHICKEN - FOOD
           HAMBURGER - FOOD
           YOGURT - FOOD
           SCALLOP - FOOD
           RICE - FOOD
           GUAVA - FOOD
           TRIUMPH - PLEASURE
           INTOXICATION - PLEASURE
           EXPECTATION - PLEASURE
           EXCITEMENT - PLEASURE
           ACHIEVEMENT - PLEASURE
           PROSTATITIS - PAIN
           DREAD - PAIN
           LACERATION - PAIN
           ANXIETY - PAIN
           BOILS - PAIN
           SCIATICA - PAIN
           ABRASION - PAIN
           QUEBEC - OBJECT
           GOIAS - OBJECT
           MANITOBA - OBJECT
           SURREY - OBJECT
           PENNSYLVANIA - OBJECT
           ALSACE - OBJECT
           GUANABARA - OBJECT
           ARIZONA - OBJECT
           OREGON - OBJECT
           BOSNIA - OBJECT
           BAVARIA - OBJECT
           MORAVIA - OBJECT
           KENTUCKY - OBJECT
           MARS - PLANET
           VULCAN - PLANET
           NEPTUNE - PLANET
           VENUS - PLANET)

 (:INIT
  (PROVINCE QUEBEC)
  (PROVINCE GOIAS)
  (PROVINCE MANITOBA)
  (PROVINCE SURREY)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE ALSACE)
  (PROVINCE GUANABARA)
  (PROVINCE ARIZONA)
  (PROVINCE OREGON)
  (PROVINCE BOSNIA)
  (PROVINCE BAVARIA)
  (PROVINCE MORAVIA)
  (PROVINCE KENTUCKY)
  (EATS HOTDOG CUCUMBER)
  (LOCALE BAGUETTE GUANABARA)
  (LOCALE HAMBURGER BAVARIA)
  (EATS MUFFIN BAGUETTE)
  (EATS BAGUETTE MUFFIN)
  (EATS RICE SCALLOP)
  (CRAVES PROSTATITIS CUCUMBER)
  (CRAVES INTOXICATION BEEF)
  (ATTACKS SURREY PENNSYLVANIA)
  (LOCALE MUFFIN OREGON)
  (EATS GUAVA YOGURT)
  (EATS TURKEY CHICKEN)
  (CRAVES SCIATICA YOGURT)
  (ATTACKS QUEBEC GOIAS)
  (CRAVES EXCITEMENT YOGURT)
  (CRAVES ANXIETY CHICKEN)
  (EATS TURKEY MUFFIN)
  (EATS BEEF HAMBURGER)
  (EATS BAGUETTE RICE)
  (EATS HAMBURGER HOTDOG)
  (EATS MUTTON CHICKEN)
  (HARMONY EXCITEMENT VENUS)
  (HARMONY TRIUMPH VULCAN)
  (LOCALE GUAVA OREGON)
  (LOCALE HOTDOG KENTUCKY)
  (EATS MUTTON HOTDOG)
  (EATS CHICKEN HOTDOG)
  (EATS GUAVA RICE)
  (ATTACKS ARIZONA OREGON)
  (EATS HOTDOG HAMBURGER)
  (EATS MUFFIN TURKEY)
  (EATS CUCUMBER HOTDOG)
  (EATS RICE BAGUETTE)
  (EATS BEEF BAGUETTE)
  (CRAVES TRIUMPH TURKEY)
  (ATTACKS GUANABARA ARIZONA)
  (EATS TURKEY CUCUMBER)
  (EATS BAGUETTE BEEF)
  (EATS SCALLOP YOGURT)
  (EATS HAMBURGER BEEF)
  (EATS BEEF HOTDOG)
  (LOCALE CHICKEN SURREY)
  (ATTACKS ALSACE GUANABARA)
  (ATTACKS MANITOBA SURREY)
  (CRAVES ACHIEVEMENT GUAVA)
  (LOCALE TURKEY PENNSYLVANIA)
  (EATS CUCUMBER BAGUETTE)
  (EATS CHICKEN MUTTON)
  (EATS BAGUETTE CUCUMBER)
  (ATTACKS MORAVIA KENTUCKY)
  (ORBITS NEPTUNE VENUS)
  (HARMONY EXPECTATION VENUS)
  (EATS SCALLOP RICE)
  (LOCALE YOGURT BOSNIA)
  (ATTACKS OREGON BOSNIA)
  (EATS CHICKEN TURKEY)
  (ATTACKS BOSNIA BAVARIA)
  (CRAVES DREAD BAGUETTE)
  (ATTACKS BAVARIA MORAVIA)
  (EATS HOTDOG BEEF)
  (HARMONY ACHIEVEMENT VULCAN)
  (CRAVES ABRASION GUAVA)
  (ATTACKS GOIAS MANITOBA)
  (EATS RICE GUAVA)
  (CRAVES EXPECTATION HAMBURGER)
  (EATS CUCUMBER TURKEY)
  (ORBITS VULCAN NEPTUNE)
  (HARMONY INTOXICATION VENUS)
  (EATS YOGURT GUAVA)
  (EATS HOTDOG CHICKEN)
  (LOCALE CUCUMBER BAVARIA)
  (EATS YOGURT SCALLOP)
  (ORBITS MARS VULCAN)
  (LOCALE BEEF BAVARIA)
  (LOCALE MUTTON GOIAS)
  (LOCALE SCALLOP OREGON)
  (LOCALE RICE GUANABARA)
  (CRAVES LACERATION MUFFIN)
  (ATTACKS PENNSYLVANIA ALSACE)
  (EATS HOTDOG MUTTON)
  (CRAVES BOILS HAMBURGER))
 (:GOAL
  (AND (CRAVES DREAD MUTTON)
       (CRAVES BOILS MUTTON)
       (CRAVES ANXIETY CHICKEN))))