(DEFINE (PROBLEM STRIPS-MYSTY-X-12)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS BROCCOLI - FOOD
           TURKEY - FOOD
           LETTUCE - FOOD
           KALE - FOOD
           HOTDOG - FOOD
           PORK - FOOD
           WURST - FOOD
           ARUGULA - FOOD
           EXCITEMENT - PLEASURE
           INTOXICATION - PLEASURE
           LOVE - PLEASURE
           REST - PLEASURE
           ABRASION - PAIN
           GRIEF - PAIN
           ANGER - PAIN
           KENTUCKY - OBJECT
           PENNSYLVANIA - OBJECT
           QUEBEC - OBJECT
           ARIZONA - OBJECT
           SURREY - OBJECT
           GUANABARA - OBJECT
           GOIAS - OBJECT
           PLUTO - PLANET
           JUPITER - PLANET
           NEPTUNE - PLANET)

 (:INIT
  (PROVINCE KENTUCKY)
  (PROVINCE PENNSYLVANIA)
  (PROVINCE QUEBEC)
  (PROVINCE ARIZONA)
  (PROVINCE SURREY)
  (PROVINCE GUANABARA)
  (PROVINCE GOIAS)
  (EATS LETTUCE ARUGULA)
  (LOCALE WURST GOIAS)
  (ATTACKS SURREY GUANABARA)
  (LOCALE PORK PENNSYLVANIA)
  (LOCALE LETTUCE SURREY)
  (EATS HOTDOG KALE)
  (ATTACKS GUANABARA GOIAS)
  (CRAVES ABRASION HOTDOG)
  (EATS WURST BROCCOLI)
  (HARMONY REST JUPITER)
  (ATTACKS QUEBEC ARIZONA)
  (CRAVES EXCITEMENT BROCCOLI)
  (HARMONY INTOXICATION JUPITER)
  (EATS BROCCOLI WURST)
  (EATS ARUGULA WURST)
  (EATS TURKEY BROCCOLI)
  (CRAVES LOVE HOTDOG)
  (EATS PORK WURST)
  (ORBITS PLUTO JUPITER)
  (EATS HOTDOG LETTUCE)
  (CRAVES ANGER ARUGULA)
  (EATS KALE PORK)
  (EATS LETTUCE WURST)
  (HARMONY LOVE JUPITER)
  (CRAVES GRIEF HOTDOG)
  (CRAVES REST ARUGULA)
  (LOCALE BROCCOLI QUEBEC)
  (EATS LETTUCE HOTDOG)
  (LOCALE TURKEY ARIZONA)
  (EATS KALE HOTDOG)
  (LOCALE KALE PENNSYLVANIA)
  (CRAVES INTOXICATION LETTUCE)
  (ATTACKS PENNSYLVANIA QUEBEC)
  (EATS WURST LETTUCE)
  (EATS BROCCOLI TURKEY)
  (EATS PORK KALE)
  (EATS WURST ARUGULA)
  (ATTACKS KENTUCKY PENNSYLVANIA)
  (HARMONY EXCITEMENT NEPTUNE)
  (ORBITS JUPITER NEPTUNE)
  (EATS TURKEY HOTDOG)
  (EATS ARUGULA LETTUCE)
  (LOCALE HOTDOG PENNSYLVANIA)
  (LOCALE ARUGULA KENTUCKY)
  (EATS WURST PORK)
  (EATS HOTDOG TURKEY)
  (ATTACKS ARIZONA SURREY))
 (:GOAL (AND (CRAVES ANGER KALE))))