(DEFINE (PROBLEM STRIPS-MYSTY-X-3)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS PEPPER - FOOD
           PEA - FOOD
           LEMON - FOOD
           SNICKERS - FOOD
           MARZIPAN - FOOD
           POPOVER - FOOD
           MELON - FOOD
           ORANGE - FOOD
           CHOCOLATE - FOOD
           HAM - FOOD
           MUTTON - FOOD
           ENTERTAINMENT - PLEASURE
           TRIUMPH - PLEASURE
           LOVE - PLEASURE
           SATISFACTION - PLEASURE
           LACERATION - PAIN
           ANXIETY - PAIN
           GRIEF - PAIN
           DEPRESSION - PAIN
           BOILS - PAIN
           ANGINA - PAIN
           HANGOVER - PAIN
           JEALOUSY - PAIN
           GOIAS - OBJECT
           GUANABARA - OBJECT
           BAVARIA - OBJECT
           ARIZONA - OBJECT
           MANITOBA - OBJECT
           VULCAN - PLANET
           VENUS - PLANET
           NEPTUNE - PLANET)

 (:INIT
  (PROVINCE GOIAS)
  (PROVINCE GUANABARA)
  (PROVINCE BAVARIA)
  (PROVINCE ARIZONA)
  (PROVINCE MANITOBA)
  (EATS ORANGE MUTTON)
  (HARMONY SATISFACTION NEPTUNE)
  (CRAVES ANGINA ORANGE)
  (CRAVES GRIEF MARZIPAN)
  (EATS PEA SNICKERS)
  (EATS POPOVER PEPPER)
  (ATTACKS GUANABARA BAVARIA)
  (EATS MUTTON ORANGE)
  (ATTACKS BAVARIA ARIZONA)
  (ATTACKS GOIAS GUANABARA)
  (HARMONY TRIUMPH NEPTUNE)
  (EATS MARZIPAN PEA)
  (LOCALE POPOVER ARIZONA)
  (LOCALE HAM MANITOBA)
  (EATS MUTTON MELON)
  (CRAVES JEALOUSY HAM)
  (EATS PEA PEPPER)
  (EATS PEPPER MELON)
  (LOCALE MELON MANITOBA)
  (LOCALE PEA BAVARIA)
  (CRAVES BOILS MELON)
  (EATS POPOVER LEMON)
  (CRAVES LACERATION PEPPER)
  (EATS POPOVER MARZIPAN)
  (EATS CHOCOLATE HAM)
  (LOCALE MUTTON GUANABARA)
  (EATS MELON HAM)
  (ORBITS VENUS NEPTUNE)
  (HARMONY LOVE NEPTUNE)
  (EATS MARZIPAN SNICKERS)
  (EATS PEPPER POPOVER)
  (LOCALE LEMON GOIAS)
  (CRAVES TRIUMPH POPOVER)
  (ORBITS VULCAN VENUS)
  (EATS HAM MELON)
  (LOCALE MARZIPAN BAVARIA)
  (EATS CHOCOLATE ORANGE)
  (EATS MARZIPAN POPOVER)
  (EATS ORANGE CHOCOLATE)
  (EATS SNICKERS PEA)
  (EATS PEA MARZIPAN)
  (HARMONY ENTERTAINMENT VENUS)
  (EATS LEMON PEA)
  (EATS MELON PEPPER)
  (LOCALE ORANGE BAVARIA)
  (CRAVES LOVE ORANGE)
  (CRAVES ANXIETY SNICKERS)
  (LOCALE PEPPER MANITOBA)
  (EATS MELON MUTTON)
  (EATS PEPPER PEA)
  (LOCALE CHOCOLATE GUANABARA)
  (EATS HAM CHOCOLATE)
  (CRAVES ENTERTAINMENT PEPPER)
  (EATS SNICKERS MARZIPAN)
  (ATTACKS ARIZONA MANITOBA)
  (CRAVES SATISFACTION MUTTON)
  (EATS LEMON POPOVER)
  (LOCALE SNICKERS BAVARIA)
  (EATS PEA LEMON)
  (CRAVES DEPRESSION POPOVER)
  (CRAVES HANGOVER CHOCOLATE))
 (:GOAL (AND (CRAVES HANGOVER HAM))))