(DEFINE (PROBLEM STRIPS-MYSTY-X-5)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS BROCCOLI - FOOD
           CHOCOLATE - FOOD
           TURKEY - FOOD
           TUNA - FOOD
           SWEETROLL - FOOD
           SHRIMP - FOOD
           CHERRY - FOOD
           SCALLOP - FOOD
           SATISFACTION - PLEASURE
           EXCITEMENT - PLEASURE
           INTOXICATION - PLEASURE
           LUBRICITY - PLEASURE
           SCIATICA - PAIN
           ANXIETY - PAIN
           GRIEF - PAIN
           BOILS - PAIN
           DEPRESSION - PAIN
           ABRASION - PAIN
           PROSTATITIS - PAIN
           ANGINA - PAIN
           JEALOUSY - PAIN
           LACERATION - PAIN
           ANGER - PAIN
           GRIEF-2 - PAIN
           DREAD - PAIN
           LONELINESS - PAIN
           HANGOVER - PAIN
           ALSACE - OBJECT
           KENTUCKY - OBJECT
           GOIAS - OBJECT
           ARIZONA - OBJECT
           URANUS - PLANET
           MERCURY - PLANET
           EARTH - PLANET
           MARS - PLANET)

 (:INIT
  (PROVINCE ALSACE)
  (PROVINCE KENTUCKY)
  (PROVINCE GOIAS)
  (PROVINCE ARIZONA)
  (EATS SCALLOP CHERRY)
  (CRAVES SATISFACTION BROCCOLI)
  (HARMONY EXCITEMENT MARS)
  (CRAVES JEALOUSY SHRIMP)
  (EATS TUNA BROCCOLI)
  (EATS SWEETROLL SCALLOP)
  (CRAVES GRIEF BROCCOLI)
  (ATTACKS KENTUCKY GOIAS)
  (CRAVES INTOXICATION TUNA)
  (ATTACKS ALSACE KENTUCKY)
  (EATS CHERRY SHRIMP)
  (ORBITS URANUS MERCURY)
  (EATS SHRIMP SWEETROLL)
  (LOCALE TUNA ARIZONA)
  (EATS CHERRY SCALLOP)
  (CRAVES HANGOVER SCALLOP)
  (HARMONY LUBRICITY EARTH)
  (CRAVES EXCITEMENT TURKEY)
  (CRAVES LONELINESS SCALLOP)
  (EATS BROCCOLI CHOCOLATE)
  (CRAVES DEPRESSION TURKEY)
  (EATS TUNA TURKEY)
  (EATS CHOCOLATE SHRIMP)
  (CRAVES LUBRICITY SWEETROLL)
  (LOCALE CHERRY KENTUCKY)
  (EATS TURKEY CHOCOLATE)
  (ATTACKS GOIAS ARIZONA)
  (EATS SHRIMP CHERRY)
  (CRAVES DREAD SCALLOP)
  (CRAVES GRIEF-2 SCALLOP)
  (CRAVES ANGINA SHRIMP)
  (HARMONY SATISFACTION EARTH)
  (EATS CHOCOLATE TURKEY)
  (EATS CHOCOLATE BROCCOLI)
  (ORBITS MERCURY EARTH)
  (CRAVES LACERATION SHRIMP)
  (CRAVES ANXIETY BROCCOLI)
  (LOCALE SCALLOP ALSACE)
  (CRAVES PROSTATITIS TURKEY)
  (CRAVES BOILS BROCCOLI)
  (LOCALE SHRIMP KENTUCKY)
  (EATS SWEETROLL SHRIMP)
  (LOCALE TURKEY KENTUCKY)
  (LOCALE BROCCOLI ARIZONA)
  (EATS BROCCOLI TUNA)
  (CRAVES ABRASION TURKEY)
  (LOCALE CHOCOLATE GOIAS)
  (EATS SCALLOP SWEETROLL)
  (HARMONY INTOXICATION EARTH)
  (EATS SHRIMP CHOCOLATE)
  (CRAVES ANGER CHERRY)
  (LOCALE SWEETROLL ALSACE)
  (CRAVES SCIATICA BROCCOLI)
  (ORBITS EARTH MARS)
  (EATS TURKEY TUNA))
 (:GOAL
  (AND (CRAVES LONELINESS SHRIMP)
       (CRAVES GRIEF SHRIMP))))