(DEFINE (PROBLEM STRIPS-MYSTY-X-20)
 (:DOMAIN MYSTERY-STRIPS)
 (:OBJECTS MUTTON - FOOD
           COD - FOOD
           MUFFIN - FOOD
           TUNA - FOOD
           PORK - FOOD
           SWEETROLL - FOOD
           YOGURT - FOOD
           WONDERBREAD - FOOD
           TURKEY - FOOD
           PEPPER - FOOD
           RICE - FOOD
           GUAVA - FOOD
           POTATO - FOOD
           ORANGE - FOOD
           BAGUETTE - FOOD
           SCALLION - FOOD
           MARZIPAN - FOOD
           CHERRY - FOOD
           LOVE - PLEASURE
           CURIOSITY - PLEASURE
           AESTHETICS - PLEASURE
           EMPATHY - PLEASURE
           SATISFACTION - PLEASURE
           TRIUMPH - PLEASURE
           INTOXICATION - PLEASURE
           LUBRICITY - PLEASURE
           EXPECTATION - PLEASURE
           UNDERSTANDING - PLEASURE
           ACHIEVEMENT - PLEASURE
           DREAD - PAIN
           ABRASION - PAIN
           GRIEF - PAIN
           LACERATION - PAIN
           MANITOBA - OBJECT
           GUANABARA - OBJECT
           QUEBEC - OBJECT
           ALSACE - OBJECT
           KENTUCKY - OBJECT
           MORAVIA - OBJECT
           BOSNIA - OBJECT
           GOIAS - OBJECT
           ARIZONA - OBJECT
           OREGON - OBJECT
           SURREY - OBJECT
           BAVARIA - OBJECT
           SATURN - PLANET
           NEPTUNE - PLANET
           VENUS - PLANET
           PLUTO - PLANET)

 (:INIT
  (PROVINCE MANITOBA)
  (PROVINCE GUANABARA)
  (PROVINCE QUEBEC)
  (PROVINCE ALSACE)
  (PROVINCE KENTUCKY)
  (PROVINCE MORAVIA)
  (PROVINCE BOSNIA)
  (PROVINCE GOIAS)
  (PROVINCE ARIZONA)
  (PROVINCE OREGON)
  (PROVINCE SURREY)
  (PROVINCE BAVARIA)
  (EATS PEPPER GUAVA)
  (LOCALE YOGURT ARIZONA)
  (EATS TURKEY GUAVA)
  (CRAVES TRIUMPH YOGURT)
  (HARMONY LOVE NEPTUNE)
  (CRAVES ABRASION WONDERBREAD)
  (LOCALE PORK QUEBEC)
  (LOCALE GUAVA GOIAS)
  (EATS MARZIPAN COD)
  (EATS YOGURT TUNA)
  (LOCALE COD GOIAS)
  (EATS CHERRY TURKEY)
  (ORBITS SATURN NEPTUNE)
  (LOCALE TUNA ARIZONA)
  (EATS TURKEY TUNA)
  (EATS PORK COD)
  (HARMONY INTOXICATION VENUS)
  (EATS TURKEY CHERRY)
  (ATTACKS OREGON SURREY)
  (ATTACKS SURREY BAVARIA)
  (LOCALE MARZIPAN MORAVIA)
  (HARMONY ACHIEVEMENT VENUS)
  (CRAVES DREAD YOGURT)
  (ATTACKS BOSNIA GOIAS)
  (ATTACKS GOIAS ARIZONA)
  (EATS TURKEY RICE)
  (EATS COD TUNA)
  (LOCALE POTATO SURREY)
  (CRAVES INTOXICATION WONDERBREAD)
  (HARMONY EMPATHY NEPTUNE)
  (ATTACKS ALSACE KENTUCKY)
  (LOCALE ORANGE QUEBEC)
  (EATS ORANGE SCALLION)
  (EATS PEPPER CHERRY)
  (EATS MUTTON PORK)
  (EATS COD PORK)
  (EATS MARZIPAN ORANGE)
  (EATS BAGUETTE GUAVA)
  (LOCALE PEPPER BAVARIA)
  (EATS RICE POTATO)
  (LOCALE TURKEY ALSACE)
  (EATS RICE TURKEY)
  (EATS SWEETROLL TUNA)
  (ATTACKS MORAVIA BOSNIA)
  (ORBITS VENUS PLUTO)
  (CRAVES EXPECTATION ORANGE)
  (EATS YOGURT MUFFIN)
  (EATS MARZIPAN CHERRY)
  (HARMONY LUBRICITY PLUTO)
  (EATS POTATO SCALLION)
  (EATS TUNA TURKEY)
  (EATS TUNA COD)
  (HARMONY TRIUMPH VENUS)
  (EATS SCALLION ORANGE)
  (EATS MUFFIN SWEETROLL)
  (LOCALE WONDERBREAD BOSNIA)
  (LOCALE SCALLION SURREY)
  (CRAVES GRIEF TURKEY)
  (LOCALE MUTTON QUEBEC)
  (LOCALE CHERRY GOIAS)
  (EATS MUFFIN YOGURT)
  (HARMONY AESTHETICS NEPTUNE)
  (EATS YOGURT WONDERBREAD)
  (EATS SWEETROLL MUFFIN)
  (EATS TUNA SWEETROLL)
  (EATS SCALLION POTATO)
  (EATS BAGUETTE RICE)
  (EATS CHERRY PEPPER)
  (EATS PORK MUTTON)
  (EATS POTATO RICE)
  (CRAVES ACHIEVEMENT CHERRY)
  (EATS SWEETROLL PORK)
  (EATS TUNA YOGURT)
  (CRAVES UNDERSTANDING MARZIPAN)
  (EATS ORANGE MARZIPAN)
  (ATTACKS QUEBEC ALSACE)
  (CRAVES CURIOSITY COD)
  (ORBITS NEPTUNE VENUS)
  (ATTACKS KENTUCKY MORAVIA)
  (LOCALE MUFFIN ARIZONA)
  (EATS WONDERBREAD YOGURT)
  (EATS GUAVA BAGUETTE)
  (CRAVES EMPATHY PORK)
  (LOCALE RICE MANITOBA)
  (HARMONY EXPECTATION VENUS)
  (ATTACKS MANITOBA GUANABARA)
  (EATS GUAVA PEPPER)
  (HARMONY SATISFACTION VENUS)
  (EATS PORK SWEETROLL)
  (EATS WONDERBREAD MUTTON)
  (CRAVES SATISFACTION SWEETROLL)
  (LOCALE BAGUETTE QUEBEC)
  (EATS RICE BAGUETTE)
  (LOCALE SWEETROLL GOIAS)
  (CRAVES AESTHETICS MUFFIN)
  (EATS COD MARZIPAN)
  (ATTACKS ARIZONA OREGON)
  (CRAVES LACERATION CHERRY)
  (HARMONY CURIOSITY NEPTUNE)
  (CRAVES LUBRICITY RICE)
  (CRAVES LOVE MUTTON)
  (EATS MUTTON WONDERBREAD)
  (EATS GUAVA TURKEY)
  (ATTACKS GUANABARA QUEBEC)
  (EATS CHERRY MARZIPAN)
  (HARMONY UNDERSTANDING NEPTUNE))
 (:GOAL (AND (CRAVES ABRASION PEPPER))))